version: '3.9'
services:
  strapi:
    # image: strapi/strapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz-backend
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: quiz
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./backend:/usr/src/quiz/backend
    ports:
      - '1337:1337'
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - quiz

  db:
    image: mariadb
    container_name: quiz-mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: random
      MARIADB_DATABASE: quiz
      MARIADB_USER: strapi
      MARIADB_PASSWORD: strapi
    ports:
      - 3306:3306
    volumes: 
      - quiz-db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - quiz

  adminer:
    image: adminer
    container_name: quiz-adminer
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - quiz

volumes:
  quiz-db:
networks:
  quiz: