version: '3.9'
services:
  strapi:
    # image: strapi/strapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz-backend
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: quiz
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./backend:/usr/src/quiz/backend
    ports:
      - '1347:1337'
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - quiz
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: esd-quiz-frontend
    restart: unless-stopped
    environment: 
      REACT_APP_URL_API : http://localhost:1337
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    ports: 
      - '2000:80'
    networks:
      - quiz


  db:
    image: mariadb
    container_name: quiz-mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: random
      MARIADB_DATABASE: quiz
      MARIADB_USER: strapi
      MARIADB_PASSWORD: strapi
    ports:
      - 3306:3306
    volumes: 
      - quiz-db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - quiz

  adminer:
    image: adminer
    container_name: quiz-adminer
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - quiz

volumes:
  quiz-db:
networks:
  quiz:
